INHERIT: docs/mkdocs-base.yml

site_name: cvxcla
site_url: https://www.cvxgrp.org/cvxcla/
repo_url: https://github.com/cvxgrp/cvxcla
repo_name: cvxgrp/cvxcla

docs_dir: docs

theme:
  name: material
  logo: assets/rhiza-logo.svg
  favicon: assets/rhiza-logo.svg

nav:
  - Home: index.md
  - Factor backend: factor.md
  - Paper: https://github.com/cvxgrp/cvxcla/blob/paper/cla.pdf
  - Notebooks:
    - CLA: notebooks/cla.html
    - Factor: notebooks/factor.html
  - Reports:
    - Test Report: reports/html-report/report.html
    - Coverage Report: reports/html-coverage/index.html
