# Workflow for building and deploying the book
# This workflow is triggered on push events to the repository

name: "book"

# Trigger the workflow on push events
# This ensures the documentation is automatically updated whenever code changes are pushed to main
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  marimo:
    runs-on: "ubuntu-latest"
    steps:
      - uses: jebel-quant/marimushka@v0.1.2
        with:
          notebooks: 'book/marimo'

  # Job to run tests and generate coverage reports
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.73

      - uses: tschm/cradle/actions/coverage@v0.1.73
        with:
          tests-folder: tests
          source-folder: cvxcla


  # Job to generate API documentation using pdoc
  pdoc:
    runs-on: ubuntu-latest
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.73

      - uses: tschm/cradle/actions/pdoc@v0.1.73


  book:
    # Combine all documentation and publish to GitHub Pages
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, marimo]  # Wait for all other jobs to complete

    permissions:
      contents: read
      pages: write            # Permission to deploy to Pages
      id-token: write         # Permission to verify deployment origin

    steps:
      - # Skip publish on forks
        name: Skip on fork
        if: ${{ github.event.repository.fork }}
        run: echo "This is a fork; skipping publish." && exit 0

      - uses: tschm/cradle/actions/book@v0.1.75
        if: ${{ !github.event.repository.fork }}
        with:
          title: "cvxRisk"
          links: |
            {
              "API": "./pdoc/index.html"
            }
