# Workflow for building and deploying the book
# This workflow is triggered on push events to the repository

name: "book"

# Trigger the workflow on push events
# This ensures the documentation is automatically updated whenever code changes are pushed to main
on:
  push:
    branches:
      - main

jobs:
  # Job to process marimo notebooks
  marimo:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.71


      - name: Create output directory
        shell: bash
        run: |
          mkdir -p artifacts/marimo

      - name: Convert Marimo files to HTML
        shell: bash
        run: |
          marimo export html book/marimo/cla.py -o artifacts/marimo/index.html --include-code
          ls -all artifacts/marimo

      - name: Upload HTML artifacts
        uses: actions/upload-artifact@v4
        with:
          name: marimo
          path: artifacts/marimo
          retention-days: 1

  # Job to run tests and generate coverage reports
  test:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.71

      - uses: tschm/cradle/actions/coverage@v0.1.71
        with:
          tests-folder: tests
          source-folder: cvx


  # Job to process Jupyter notebooks
  jupyter:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.71

      - uses: tschm/cradle/actions/jupyter@v0.1.71

  # Job to generate API documentation using pdoc
  pdoc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.71

      - uses: tschm/cradle/actions/pdoc@v0.1.71


  book:
    runs-on: "ubuntu-latest"
    # This job depends on the completion of test, pdoc, and jupyter jobs
    needs: [test, pdoc, jupyter, marimo]

    environment:
      name: github-pages

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      # Step: Upload the generated documentation book
      # Skipped when running locally with 'act' to prevent accidental deployments
      - name: Upload the book
        uses: tschm/cradle/actions/book@v0.1.71
