# Workflow for building and deploying the book
# This workflow is triggered on push events to the repository

name: "book"

# Trigger the workflow on push events
# This ensures the documentation is automatically updated whenever code changes are pushed to main
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  marimo:
    runs-on: "ubuntu-latest"
    steps:
      - uses: jebel-quant/marimushka@v0.1.2
        with:
          notebooks: 'book/marimo'

  # Job to run tests and generate coverage reports
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.73

      - uses: tschm/cradle/actions/coverage@v0.1.73
        with:
          tests-folder: tests
          source-folder: cvxcla


  # Job to generate API documentation using pdoc
  pdoc:
    runs-on: ubuntu-latest
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.73

      - uses: tschm/cradle/actions/pdoc@v0.1.73


  book:
    runs-on: "ubuntu-latest"
    # This job depends on the completion of test, pdoc, and jupyter jobs
    needs: [test, pdoc, marimo]

    environment:
      name: github-pages

    permissions:
      pages: write
      id-token: write

    steps:
      # Step: Upload the generated documentation book
      # Skipped when running locally with 'act' to prevent accidental deployments
      - name: Upload the book
        uses: tschm/cradle/actions/book@v0.1.75
        with:
          title: "cvxcla"
          links: |
            {
                "API": "./pdoc/index.html"
            }
