# Workflow for building and deploying the book
# This workflow is triggered on push events to the repository

name: "book"

on:
- push

jobs:
  # Job to process marimo notebooks
  marimo:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/marimo@v2.2.8


  # Job to run tests and generate coverage reports
  test:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/coverage@v2.2.8


  # Job to process Jupyter notebooks
  jupyter:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/jupyter@v2.2.8

  # Job to generate API documentation using pdoc
  pdoc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/pdoc@v2.2.8


  # Final job to build and deploy the book
  # This job runs only after all other jobs have completed successfully
  book:
    runs-on: "ubuntu-latest"
    needs: [test, jupyter, marimo, pdoc]

    permissions:
      contents: write
      pages: write

    steps:
      - uses: cvxgrp/.github/actions/book@v2.2.8
