# Workflow for building and deploying the book
# This workflow is triggered on push events to the repository

name: "book"

# Trigger the workflow on push events
# This ensures the documentation is automatically updated whenever code changes are pushed to main
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  # Job to process marimo notebooks
  marimo:
    runs-on: "ubuntu-latest"
    steps:
      # Step: Set up the virtual environment
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.72

      - name: Export notebook via wasm
        run: |
          # export all .py files in book/marimo directory
          for py_file in book/marimo/*.py; do
            if [ -f "$py_file" ]; then
              filename=$(basename "$py_file" .py)
              echo "Processing $py_file"
              mkdir -p "artifacts/marimo/$filename"
              uvx marimo export html-wasm --sandbox "$py_file" -o "artifacts/marimo/$filename" --mode edit
            fi
          done

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: marimo
          path: artifacts/marimo
          retention-days: 1

  # Job to run tests and generate coverage reports
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.72

      - uses: tschm/cradle/actions/coverage@v0.1.72
        with:
          tests-folder: tests
          source-folder: cvx


  # Job to process Jupyter notebooks
  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.72

      - uses: tschm/cradle/actions/jupyter@v0.1.72

  # Job to generate API documentation using pdoc
  pdoc:
    runs-on: ubuntu-latest
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.72

      - uses: tschm/cradle/actions/pdoc@v0.1.72


  book:
    runs-on: "ubuntu-latest"
    # This job depends on the completion of test, pdoc, and jupyter jobs
    needs: [test, pdoc, jupyter, marimo]

    environment:
      name: github-pages

    permissions:
      pages: write
      id-token: write

    steps:
      # Step: Upload the generated documentation book
      # Skipped when running locally with 'act' to prevent accidental deployments
      - name: Upload the book
        uses: tschm/cradle/actions/book@v0.1.72
