# Workflow for creating a new release version and publishing to PyPI
name: Bump version and publish

# This workflow is manually triggered
on:
  workflow_dispatch

jobs:
  # Create a new version tag based on semantic versioning
  tagging:
    # Need write permissions to create tags in the repository
    permissions:
      contents: write

    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_step.outputs.new_tag }}  # Output the new tag for use in subsequent jobs

    steps:
      # Generate a new version tag based on commit history
      - name: Generate Tag
        uses: tschm/cradle/actions/tag@v0.1.72
        id: tag_step
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    # Package building job
    # Builds the Python package with the new version tag
    runs-on: ubuntu-latest
    needs: tagging  # Depends on the tagging job to get the new version
    steps:
      - name: build
        uses: tschm/cradle/actions/build@v0.1.72  # Use the build action to build the package
        with:
          tag: ${{ needs.tagging.outputs.new_tag }}  # Use the tag from the tagging job

  # Publish the package to PyPI
  publish:
    # This job runs after the tag job completes successfully
    needs: build
    runs-on: ubuntu-latest
    # Use the release environment for PyPI credentials
    environment: release

    permissions:
      # Read access to repository contents
      contents: read
      # This permission is required for trusted publishing to PyPI
      id-token: write

    steps:
      # Download the built distribution package
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      # Publish the package to PyPI using trusted publishing
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
