name: Bump version and publish

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "CI" ]
    types: [ completed ]

jobs:
  tag:
    permissions:
      contents: write

    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.head_branch == 'main')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Generate Tag
        uses: cvxgrp/.github/actions/uv/tag@v2.0.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
