name: Bump version

on:
  workflow_dispatch

jobs:
  tag:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/uv/environment@v2.1.1

      - name: Generate Tag
        uses: cvxgrp/.github/actions/tag@v2.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
